### ISSUE TITLE
Bro plugins should support a patch version (x.y.z)

### ISSUE THREAD

**Issue by jsiwek** [bro/bro#152]
Moved from https://bro-tracker.atlassian.net/browse/BIT-1985

Created by Jon Zeolla at 2018-09-06T09:01:40.307-0500:
> Since the project and downstream projects such as `bro-pkg` seems to align with semver, plugins should be able to have a MAJOR.MINOR.PATCH version.  I suggest adding an optional PATCH version.
> 
> A quick review pointed me to the following, but I'm sure there will be some downstream changes and btests to put together:
> 
> https://github.com/bro/bro/blob/b99be6458b3fe83284b5262ca0391bf3cc99f7c2/src/plugin/Plugin.h#L66-L82
> https://github.com/bro/bro/blob/b99be6458b3fe83284b5262ca0391bf3cc99f7c2/doc/devel/plugins.rst
> https://github.com/bro/bro/blob/b99be6458b3fe83284b5262ca0391bf3cc99f7c2/CMakeLists.txt#L61-L65
> https://github.com/bro/bro/blob/b99be6458b3fe83284b5262ca0391bf3cc99f7c2/src/plugin/Plugin.cc#L442-L449
> 
> My apologies if this is a duplicate, did a quick search and couldn't find it but was on pretty slow Internet at the time.

**Comment by JonZeolla** [comment]
@jsiwek would you mind assigning this one to me?

**Comment by jsiwek** [comment]
@JonZeolla Nice, thanks for looking into it.  For toggling the GitHub assignment, maybe that will be possible once you accept the read-only collaborator invite I sent (might even see if self-assign is possible afterward).

**Comment by JonZeolla** [comment]
Thanks, I accepted the invite and the PR is up.

**Comment by jsiwek** [comment]
This was fixed via #183, now in `dev/2.7` and will be in `master` after final 2.6 release.
