### ISSUE TITLE
Problem with arguments in multi-workers environment

### ISSUE THREAD

**Issue by Aglreb** [bro/bro#179]
Hi,

I've got a problem in multi-worker environment.
I've pasted code and result in the following screenshot.

This is the bug:
![capture_bro_ref_bug_2_code](https://user-images.githubusercontent.com/40199669/45867053-c7c86f80-bd82-11e8-8250-2a0e5dd8a45b.png)
with the result:
![capture_bro_ref_bug_2_result](https://user-images.githubusercontent.com/40199669/45867054-c7c86f80-bd82-11e8-9a17-3670b243440e.png)

As you can see, only the last value of the type my_rec is printed.
This is working properly if my_rec is a basic type (like string or count).
This is inspired by notice framework code.

There is the a workaround:
![capture_bro_ref_bug_1_code](https://user-images.githubusercontent.com/40199669/45867051-c72fd900-bd82-11e8-810f-5692a47e6f9f.png)
with the result:
![capture_bro_ref_bug_1_result](https://user-images.githubusercontent.com/40199669/45867052-c72fd900-bd82-11e8-9c19-06c23381c30d.png)

But with very complex record, this is not easy to do this.
And it's seems to highlight a problem in communication between workers.

Am I right, or is there another means to do this ?

Thank for your reply.

**Comment by jsiwek** [comment]
It's not just related to remote communication, it's a result of records being a reference-type and also `local` variables being scoped to entire functions/events, not just the innermost curly braces in which they are declared.  i.e. in the example, a single record value is being created and the loop is just modifying it and passing it to an event by reference.

Instead, you can use `copy()` to force a new record value to be made for each event.

For example, this standalone script also reproduces the problem and shows a potential way to address it via `copy()`:

```bro
type my_rec: record {
    c: count;
};

event my_event(r: my_rec)
    {
    print "my_event", r;
    }

event bro_init()
    {
    local i = 0;

    while ( i < 10 )
        {
        local m: my_rec;
        m$c = i;

        if ( i < 5 )
            event my_event(copy(m));
        else
            event my_event(m);

        ++i;
        }
    }
```

You might also use the named-record-constructor like you already noticed.  It can also be helpful in combinations with `&default` or `&optional` attributes applied to record fields.

I'm closing the issue as these underlying properties of the scripting language aren't likely to change soon.
