### ISSUE TITLE
logging issue with smb file read and write

### ISSUE THREAD

**Issue by javadrezaei** [bro/bro#181]
As i saw in bro SMB scripts (base/protocols/smb/main.bro), bro doesn't log FILE_READ and FILE_WRITE actions. Is there any special reason for not doing it?

	## The file actions which are logged.
	option logged_file_actions: set[Action] = {
		FILE_OPEN,
		FILE_RENAME,
		FILE_DELETE,

		PRINT_OPEN,
		PRINT_CLOSE,
	};

**Comment by jsiwek** [comment]
Possibly to just reduce the default logging volume, however you are free to try out logging those actions if you want by tuning that `SMB::logged_file_actions` variable.  See the "config framework" and "redef" docs for how to do that:

https://www.bro.org/sphinx-git/frameworks/configuration.html#declaring-options
https://www.bro.org/sphinx-git/script-reference/statements.html#keyword-redef

Or if you want to try to get more feedback about why they're not logged by default, or why it may or may not be a good idea to enable logging for them, try following up on the mailing list:

http://mailman.icsi.berkeley.edu/mailman/listinfo/bro
