### ISSUE TITLE
Building plugins without source tree doesn't honor --enable-debug

### ISSUE THREAD

**Issue by rsmmr** [bro/bro#184]
When building a Bro plugin with a Bro build tree around, `cmake/BroPluginDynamic.cmake` inspects Bro's cmake cache to infer whether to do a debug build. Without a build tree, however, it always does a release build. 

I think we should add ``--build-mode``  to `bro-config` that outputs either release or debug, and then have the plugin build system pick up on that.

**Comment by jsiwek** [comment]
The new plugin skeleton's configure script at least has a `--enable-debug` flag you can explicitly use or one can toggle it via CMake variable `BRO_PLUGIN_ENABLE_DEBUG`, but yes, would help to automate this via `bro-config`

**Comment by jsiwek** [comment]
In master now, plugin configuration should automatically check `bro-config --build_type` and set debug flags if needed.
