### ISSUE TITLE
Negative values in ISO8601 formatting when timestamp prior to Unix epoch 

### ISSUE THREAD

**Issue by jbaggs** [bro/bro#186]
The ISO8601 formatter in JSON.cc produces a negative fractional seconds component when converting times prior to the beginning of the Unix epoch. This in turn causes problems for parsers that follow the standard. 
(The transmit timestamp on NTP requests from certain client implementations, e.g. busybox is often negative.)

[JSON.cc.diff.txt](https://github.com/bro/bro/files/2463109/JSON.cc.diff.txt)

**Comment by jsiwek** [comment]
Thanks, fixed via 70233148be2a20cd6813b3f6e7b86c4d7aa677b7 in master now (will be in 2.6 release).
