### ISSUE TITLE
mysql analyzer logs tls as binary

### ISSUE THREAD

**Issue by JustinAzoff** [bro/bro#195]
Occasionally we see 500k binary lines being written to the mysql.log whenever a tls connection is in use.

cmd+arg ends up being something like

    unknown-242     \x01\x00\x00\xee\x03\x03...+500k more of data

I can see the plaintext part of a x509 cert in there as well.

I think vlad had this mostly fixed in topic/vladg/mysql_tls, but that broke normal query logging.

**Comment by grigorescu** [comment]
This is fixed in topic/vladg/mysql_nul_string_fix
