### ISSUE TITLE
bro --help returns an error code

### ISSUE THREAD

**Issue by grigorescu** [bro/bro#199]
```
$ bro --help 2> /dev/null; echo $?
1
```

Looks like the culprit is https://github.com/bro/bro/blob/ced5718071536a328576cc41344f13941afb4c8f/src/main.cc#L220

**Comment by 0xxon** [comment]
Is this a problem? Just to give an example...

```
$ grep --help; echo $?
usage: grep [-abcDEFGHhIiJLlmnOoqRSsUVvwxZ] [-A num] [-B num] [-C[num]]
	[-e pattern] [-f file] [--binary-files=value] [--color=when]
	[--context[=num]] [--directories=action] [--label] [--line-buffered]
	[--null] [pattern] [file ...]
2
```

**Comment by grigorescu** [comment]
I believe it is. It's an issue I ran into this morning, as I'm working on automating some Bro workflows and testing, and most tools interpret 1 (EXIT_FAILURE) as a failure. I'm calling '--help' to access the default environment variables Bro was installed with, so it's not just a theoretical exercise.

Here's what the [libc documentation](https://www.gnu.org/software/libc/manual/html_node/Exit-Status.html) has to say:

> There are conventions for what sorts of status values certain programs should return. The most common convention is simply 0 for success and 1 for failure.

The current behavior is unexpected, to say the least. I asked for the help message, and I got the help message.

I'd argue that grep isn't a good example for this, as the libc docs follow up the previous statement with:

> Programs that perform comparison use a different convention: they use status 1 to indicate a mismatch, and status 2 to indicate an inability to compare.

**Comment by jsiwek** [comment]
Even though I think I've seen several other tools exit non-zero on `--help` (while others exit 0), I agree it's better to exit 0.  If the full help dialog can't be displayed for some reason or it gets displayed due to invalid args, then that would be reason to exit non-zero.
