### ISSUE TITLE
contents.bro

### ISSUE THREAD

**Issue by georgiaxron** [bro/bro#220]
Hi, i am new in bro and i am trying to use an actually new script called contents.bro(3 months ago)
the path to it is: 
        bro/scripts/base/protocols/conn/contents.bro
  This script creates files in .dat extantion and i was wondering how can i read them. I 've tried some tools but all of them give me "unknown file type" error.  I am working on linux. 
Thank you in advance

**Comment by sethhall** [comment]
Those files are the raw contents of the reassembled body of the TCP connection.  You will have to parse them or otherwise understand the content in them.

You could use hexdump to look at the files like this...

```shell
$ hexdump -C yourfile.dat
```

**Comment by georgiaxron** [comment]
Thanks for the quick response that was very helpfull
